id:                        JKE-001
trigger_mode:              0
intensity_scale:           0.05
rate:                      20.0
normals_estimation_radius: 2
send_point_cloud:          true
send_normal_map:           false
send_depth_map:            true
send_confidence_map:       false
send_texture:              true
laser_power:               2000
